export const item=[
    {
        no:1,
        name:'calci',
        price:'989',
        owner:'omar',
    },
    {
        no:2,
        name:'All In One',
        price:'499',
        owner:'Aman',
    },
    {
        no:3,
        name:'Apron',
        price:'9300',
        owner:'Ali',
    },
    {
        no:4,
        name:'efg',
        price:'300',
        owner:'Ali',
    },
    {
        no:5,
        name:'hij',
        price:'300',
        owner:'Ali',
    },
    {
        no:6,
        name:'klm',
        price:'300',
        owner:'Ali',
    },
    {
        no:7,
        name:'noq',
        price:'300',
        owner:'Ali',
    },
    {
        no:8,
        name:'rst',
        price:'300',
        owner:'Ali',
    },
    {
        no:9,
        name:'uvw',
        price:'300',
        owner:'Ali',
    },
    {
        no:10,
        name:'xyz',
        price:'300',
        owner:'Ali',
    },
]
